apiVersion: v1
kind: Service
metadata:
  name: pdp-with-react-service
spec:
  type: NodePort
  selector:
    app: pdp-with-react-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 3000
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdp-with-react-app
  labels:
    app: pdp-react-app
spec:
  selector:
    matchLabels:
      app: pdp-with-react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pdp-with-react-app
    spec:
      containers:
        - name: pdp-with-react-app
          image: yakupsenates/pdp-with-react:3
          ports:
            - containerPort: 3000
